// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BBBSLI.DSS.MobileApp.Infrastructure.AppDbContext;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BBBSLI.DSS.MobileApp.Infrastructure.AppDbContext.Configurations
{
    public partial class DonationTransactionConfiguration : IEntityTypeConfiguration<DonationTransaction>
    {
        public void Configure(EntityTypeBuilder<DonationTransaction> entity)
        {
            entity.Property(e => e.Action)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Comments)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.DateCreated).HasColumnType("datetime");

                entity.Property(e => e.DateModified).HasColumnType("datetime");

                entity.Property(e => e.ModifiedBy)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.HasOne(d => d.Donation)
                    .WithMany(p => p.DonationTransaction)
                    .HasForeignKey(d => d.DonationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__DonationT__Donat__0E391C95");

                entity.HasOne(d => d.DonationStatus)
                    .WithMany(p => p.DonationTransaction)
                    .HasForeignKey(d => d.DonationStatusId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__DonationT__Donat__0EF836A4");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DonationTransaction> entity);
    }
}
