// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BBBSLI.DSS.MobileApp.Infrastructure.AppDbContext;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BBBSLI.DSS.MobileApp.Infrastructure.AppDbContext.Configurations
{
    public partial class DonationStatusConfiguration : IEntityTypeConfiguration<DonationStatus>
    {
        public void Configure(EntityTypeBuilder<DonationStatus> entity)
        {
            entity.Property(e => e.DateCreated)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.DateModified)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(25)
                    .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DonationStatus> entity);
    }
}
