// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BBBSLI.DSS.MobileApp.Infrastructure.AppDbContext;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BBBSLI.DSS.MobileApp.Infrastructure.AppDbContext.Configurations
{
    public partial class DonationConfiguration : IEntityTypeConfiguration<Donation>
    {
        public void Configure(EntityTypeBuilder<Donation> entity)
        {
            entity.ToTable(e => e.HasTrigger ( "tr_donation_Update" ) );

                entity.Property(e => e.Comments).IsUnicode(false);

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.Property(e => e.DateCreated)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.DateKey).HasDefaultValueSql("(CONVERT([int],CONVERT([char](8),getdate(),(112))))");

                entity.Property(e => e.DateModified)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.DwastatusId).HasColumnName("DWAStatusId");

                entity.Property(e => e.Instructions)
                    .HasMaxLength(2000)
                    .IsUnicode(false);

                entity.Property(e => e.IsCancel).HasDefaultValue(false);

                entity.Property(e => e.IsDoNotCall).HasDefaultValue(false);

                entity.Property(e => e.IsDwa).HasColumnName("IsDWA");

                entity.Property(e => e.IsMissedOrRescheduled).HasDefaultValue(false);

                entity.Property(e => e.MissedOrRescheduledReason)
                    .HasMaxLength(2000)
                    .IsUnicode(false);

                entity.Property(e => e.ModifiedBy)
                    .HasMaxLength(128)
                    .IsUnicode(false);

                entity.HasOne(d => d.DonationStatus)
                    .WithMany(p => p.Donation)
                    .HasForeignKey(d => d.DonationStatusId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Donation_DonationStatus");

                entity.HasOne(d => d.DonationType)
                    .WithMany(p => p.Donation)
                    .HasForeignKey(d => d.DonationTypeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Donation__Donati__04AFB25B");

                entity.HasOne(d => d.Donor)
                    .WithMany(p => p.Donation)
                    .HasForeignKey(d => d.DonorId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Donation_Donation_Donor");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Donation> entity);
    }
}
